#!/usr/bin/env perl
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';
plugin(
    'CloudStore' => {
        apikey    => 'moo',
        apisecret => 'moo',
        specifics => {bucket => 'my-s3-bucket'},
    }
);

get '/' => sub {
    my $self = shift;
    $self->cloudstore->save;
    $self->render('index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
Welcome to the Mojolicious real-time web framework!

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
